// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlmTZ7b1CITAY3iylktO93SKUDmePWXcc',
    appId: '1:419185425480:web:91ecdeda3d8bc459d7ec7d',
    messagingSenderId: '419185425480',
    projectId: 'capsoul-ebea3',
    authDomain: 'capsoul-ebea3.firebaseapp.com',
    storageBucket: 'capsoul-ebea3.firebasestorage.app',
    measurementId: 'G-235SWNETS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Ir4jUtmIBvUN1kRpP5Hc_-2g3UxiRV0',
    appId: '1:419185425480:android:62a8123c7e942623d7ec7d',
    messagingSenderId: '419185425480',
    projectId: 'capsoul-ebea3',
    storageBucket: 'capsoul-ebea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2tmqbTCQLm1-EyBvhZvgEINCspbAnG5M',
    appId: '1:419185425480:ios:3b0cf875f4a8aa21d7ec7d',
    messagingSenderId: '419185425480',
    projectId: 'capsoul-ebea3',
    storageBucket: 'capsoul-ebea3.firebasestorage.app',
    iosClientId: '419185425480-h3c7c4l5kqppcffkimhtki2qcv3t4p6a.apps.googleusercontent.com',
    iosBundleId: 'com.capsoul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2tmqbTCQLm1-EyBvhZvgEINCspbAnG5M',
    appId: '1:419185425480:ios:3b0cf875f4a8aa21d7ec7d',
    messagingSenderId: '419185425480',
    projectId: 'capsoul-ebea3',
    storageBucket: 'capsoul-ebea3.firebasestorage.app',
    iosClientId: '419185425480-h3c7c4l5kqppcffkimhtki2qcv3t4p6a.apps.googleusercontent.com',
    iosBundleId: 'com.capsoul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlmTZ7b1CITAY3iylktO93SKUDmePWXcc',
    appId: '1:419185425480:web:b0589e455b6ff7fdd7ec7d',
    messagingSenderId: '419185425480',
    projectId: 'capsoul-ebea3',
    authDomain: 'capsoul-ebea3.firebaseapp.com',
    storageBucket: 'capsoul-ebea3.firebasestorage.app',
    measurementId: 'G-ETET8T24MX',
  );
}
